export const userConstants = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    SCREEN_LOGIN: 'SCREEN_LOGIN',
    SCREEN_REGISTER: 'SCREEN_REGISTER',
    ADD_USER_INFO: 'ADD_USER_INFO',
    SCREEN_UPDATE_DEPOSIT: 'SCREEN_UPDATE_DEPOSIT',
    CLEAR_USER_INFO: 'CLEAR_USER_INFO',
}